# Site settings
author: Sean Thompson
title: AlgoRhythm
header-img: img/home-bg.png
email: sthompson2822@gmail.com
copyright_name: Sean Thompson
description: > # this means to ignore newlines until "baseurl:"
  Documenting a Journey in Development from 0 - (n-1)
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  sean-slaughter

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
